const sharp = require('sharp');

function escapeXml(str = '') {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function wrapText(text, maxCharsPerLine) {
  const words = text.split(' ');
  const lines = [];
  let current = '';
  for (const w of words) {
    if ((current + ' ' + w).trim().length > maxCharsPerLine) {
      lines.push(current.trim());
      current = w;
    } else {
      current += ' ' + w;
    }
  }
  if (current) lines.push(current.trim());
  return lines.slice(0, 4);
}

async function generateAnalysisImage(data) {
  const descLines = wrapText(data.description, 55);

  const svg = `
  <svg width="800" height="420" viewBox="0 0 800 420" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stop-color="#1f2937"/>
        <stop offset="100%" stop-color="#111827"/>
      </linearGradient>
    </defs>
    <rect width="800" height="420" rx="24" fill="url(#bg)"/>

    <text x="40" y="70" font-family="Arial, sans-serif" font-size="30" font-weight="bold" fill="#ffffff">
      ${escapeXml(data.name)}
    </text>

    <text x="40" y="105" font-family="Arial, sans-serif" font-size="16" fill="#9ca3af">
      Chrome Extension Analysis
    </text>

    <rect x="40" y="130" width="720" height="1" fill="#374151"/>

    ${descLines
      .map(
        (line, i) =>
          `<text x="40" y="${170 + i * 26}" font-family="Arial, sans-serif" font-size="16" fill="#e5e7eb">${escapeXml(
            line
          )}</text>`
      )
      .join('')}

    <g transform="translate(40, 300)">
      <rect width="220" height="80" rx="12" fill="#1e293b" stroke="#334155"/>
      <text x="20" y="30" font-family="Arial, sans-serif" font-size="14" fill="#9ca3af">Rating</text>
      <text x="20" y="60" font-family="Arial, sans-serif" font-size="26" font-weight="bold" fill="#facc15">${escapeXml(
        String(data.rating)
      )}</text>
    </g>

    <g transform="translate(290, 300)">
      <rect width="220" height="80" rx="12" fill="#1e293b" stroke="#334155"/>
      <text x="20" y="30" font-family="Arial, sans-serif" font-size="14" fill="#9ca3af">Users</text>
      <text x="20" y="60" font-family="Arial, sans-serif" font-size="26" font-weight="bold" fill="#4ade80">${escapeXml(
        String(data.users)
      )}</text>
    </g>

    <g transform="translate(540, 300)">
      <rect width="220" height="80" rx="12" fill="#1e293b" stroke="#334155"/>
      <text x="20" y="30" font-family="Arial, sans-serif" font-size="14" fill="#9ca3af">Extension ID</text>
      <text x="20" y="55" font-family="Arial, sans-serif" font-size="13" fill="#93c5fd">${escapeXml(
        data.id.slice(0, 16) + '...'
      )}</text>
    </g>

    <text x="40" y="405" font-family="Arial, sans-serif" font-size="12" fill="#6b7280">
      Generated by @extensionchrbot
    </text>
  </svg>`;

  return sharp(Buffer.from(svg)).png().toBuffer();
}

module.exports = { generateAnalysisImage };
